export const CONTENTS_RECEIVE_DATA = 'CONTENTS_RECEIVE_DATA';
export const CONTENTS_RECIVE_ERROR = 'CONTENTS_RECIVE_ERROR'
export const ADD_TASK_ERROR = 'ADD_TASK_ERROR'
export const UPDATE_TASK_ERROR = 'UPDATE_TASK_ERROR'
